### ISSUE TITLE
Switch to emotion or styled-components instead of styled-jsx.

### ISSUE THREAD

**Issue by danilyanich** [paralect/nextjs-landing-starter#5]
- [styled-components](https://github.com/styled-components/styled-components/tree/master)
- [emotion](https://github.com/emotion-js/emotion)

**Comment by ezhivitsa** [comment]
@danilyanich Not sure that we nan use this libraries in this repository because `Next.js` requires using `styled-jsx`
https://github.com/zeit/next.js/#built-in-css-support

**Comment by ezhivitsa** [comment]
One more thing. I don't like include `css` into `js` files and I don't see any advantages t this approach. I think that there is only one case where we can use such approach. This is the case when we develop a library of React components with build-in styles. In all other cases `css in js` gives us more problems instead of advantages.
But this is only me opinion.

**Comment by danilyanich** [comment]
@ezhivitsa `next.js` does not require `styled-jsx`, you can use any `css-in-js` solution (`styled-jsx` is also `css-in-js`). Also `styled-jsx` forces lots of limitations on how you write css. Consider such situation: you have a list of items, and each item must have their own styles (eg. color).

- `styled-jsx`
```javascript
<ul>
  {items.map(item => (
    <li>
      {item.text}
      <style jsx>{`
        li {
          color: ${item.color};
        }
      `}</style>
    </li>
  ))}
  <style jsx>{`
    ul {
      margin: 10px;

      /* with postcss plugin */
      li {
        color: black;
      }
    }
  `}</style>
<ul>
```

- `styled-components` or `emotion`
```javascript
const ListItem = styled.li`
  color: ${props => props.color};
`;

const List = styled.ul`
  margin: 10px;

  /* nesting included by default */
  /* component as selector with babel plugin */
  ${ListItem} {
    color: black;
  }
`;

<List>
  {items.map(item => (
    <ListItem color={item.color}>
      {item.text}
    </ListItem>
  ))}
<List>
```

Also you can split you styles into separate file, because they are plain `React` components, while `styled-jsx` has limitations on this (e.g. no dynamic styling). Also this solution supports SSR.

**Comment by anorsich** [comment]
@ezhivitsa @danilyanich @IharKrasnik Let's discuss and come with an action plan, which basically consists of three things: Why? What? Who? Let's learn to sell our ideas, as we will have to work with the broader community soon.

**Comment by ezhivitsa** [comment]
I think that now we can close this issue because now we are using CSS modules instead of CSS in JS approach.
